services:
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=odoo
    image: postgres:13-alpine
    volumes:
      - .db/:/var/lib/postgresql/data
      - ./migr-postgresql.conf:/etc/postgresql/postgresql.conf
  pgadmin:
    image: dpage/pgadmin4
    restart: 'unless-stopped'
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=odoo
  odoo:
    build: odoo
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=openupgrade14
      - RUNNING_ENV=dev
      - LIMIT_TIME_CPU=6000000
      - LIMIT_TIME_REAL=12000000
      - LIMIT_MEMORY_SOFT=5147483648
      - LIMIT_MEMORY_HARD=5684354560
    depends_on:
      - db
      - pgadmin
    ports:
      - "8069:8069"
    volumes:
      - ./odoo:/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
    labels:
      traefik.enable: true
      traefik.longpolling.frontend.rule: "Host:migration.dy;PathPrefix:/longpolling/"
      traefik.www.frontend.rule: "Host:migration.dy"
      docky.main.service: true
      docky.user: odoo

version: '3'
